const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),crypto=require('node:crypto');
let payload,transfers,requested;
const self={location:{href:'https://test.ts.net/skelecad/viewer/mesh-worker.js'},postMessage:(data,buffers)=>{payload=data;transfers=buffers;}};
const bytes=new ArrayBuffer(134),view=new DataView(bytes);view.setUint32(80,1,true);
[0,0,0,1,0,0,0,1,0].forEach((v,k)=>view.setFloat32(96+4*k,v,true));
const sha=crypto.createHash('sha256').update(Buffer.from(bytes)).digest('hex');
let input=bytes,contentHash=null;
vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../mesh-worker.js'),'utf8'),{self,URL,crypto:crypto.webcrypto,Float32Array,Uint8Array,DataView,fetch:async(url,options)=>{requested={url,options};return {ok:true,headers:{get:()=>contentHash},arrayBuffer:async()=>input};}});
(async()=>{
  await self.onmessage({data:{id:1,url:'model.stl',sha256:sha}});
  assert.equal(payload.id,1);assert.equal(payload.sha256,sha);
  assert.equal(requested.url,'https://test.ts.net/skelecad/viewer/model.stl?sha256='+sha+'&cache=shared-scale-20260912');
  assert.equal(requested.options.cache,'default');
  assert.deepEqual(Array.from(payload.mesh.positions),[0,0,0,1,0,0,0,1,0]);
  assert.deepEqual(Array.from(payload.mesh.normals),[0,0,1,0,0,1,0,0,1]);
  assert.equal(transfers[0],payload.mesh.positions.buffer);assert.equal(transfers[1],payload.mesh.normals.buffer);
  await self.onmessage({data:{id:2,url:'model.stl',sha256:'changed'}});assert.match(payload.error,/照合/);assert.equal(payload.mesh,undefined);
  input=bytes.slice(0,100);await self.onmessage({data:{id:3,url:'bad.stl'}});assert.match(payload.error,/STL/);
  input=bytes.slice(0);new DataView(input).setFloat32(96,NaN,true);
  await self.onmessage({data:{id:4,url:'bad.stl'}});assert.match(payload.error,/座標/);
  const packed=new ArrayBuffer(96),packedView=new DataView(packed),p=new Uint8Array(packed);
  p.set(Buffer.from('SKMESH1\0'));packedView.setUint32(8,3,true);packedView.setUint32(12,1,true);p.set(Buffer.from(sha,'hex'),16);
  const vertexBytes=new Uint8Array(bytes,96,36);
  for(let b=0;b<12;b++)for(let v=0;v<3;v++)p[48+b*3+v]=vertexBytes[v*12+b];
  [0,1,2].forEach((v,i)=>packedView.setUint32(84+i*4,v,true));
  input=packed;contentHash=crypto.createHash('sha256').update(Buffer.from(input)).digest('hex');
  await self.onmessage({data:{id:5,url:'model.stl',sha256:sha,compact:true}});
  assert.equal(payload.sha256,sha);assert.deepEqual(Array.from(payload.mesh.positions),[0,0,0,1,0,0,0,1,0]);
  assert.deepEqual(Array.from(payload.mesh.normals),[0,0,1,0,0,1,0,0,1]);assert.match(requested.url,/format=mesh-v1/);
  p[6]=50;contentHash=crypto.createHash('sha256').update(Buffer.from(input)).digest('hex');
  await self.onmessage({data:{id:10,url:'model.stl',sha256:sha,compact:true,preview:true}});assert.equal(payload.detail,'preview');assert.match(requested.url,/detail=preview-v3/);
  await self.onmessage({data:{id:11,url:'model.stl',sha256:sha,compact:true}});assert.match(payload.error,/精密形状/,'preview cannot enter the exact cache');
  p[6]=49;contentHash=crypto.createHash('sha256').update(Buffer.from(input)).digest('hex');
  await self.onmessage({data:{id:6,url:'model.stl',sha256:'wrong',compact:true}});assert.match(payload.error,/照合/);
  contentHash='bad';await self.onmessage({data:{id:7,url:'model.stl',compact:true}});assert.match(payload.error,/照合/);
  packedView.setUint32(84,10,true);contentHash=crypto.createHash('sha256').update(Buffer.from(input)).digest('hex');
  await self.onmessage({data:{id:8,url:'model.stl',compact:true}});assert.match(payload.error,/頂点参照/);
  input=bytes;await self.onmessage({data:{id:9,url:'model.stl',sha256:sha,compact:true}});assert.equal(payload.sha256,sha,'old servers returning STL remain compatible');
  console.log('PASS: STL/compact transport preserves faces, coordinates and source identity; corrupt payloads, stale sources and invalid indices rejected');
})().catch(error=>{console.error(error);process.exitCode=1;});
