const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const C=require('../motion-core.js'),config=JSON.parse(fs.readFileSync(path.join(__dirname,'../../config/parameters.json'),'utf8'));
const elements=new Map(),workers=[];let pickedPart='leg_right',pickDirection=null;
function element(id){if(!elements.has(id))elements.set(id,{style:{},dataset:{},hidden:false,handlers:{},addEventListener(type,fn){this.handlers[type]=fn;},getBoundingClientRect(){return {left:0,top:0,width:100,height:100};}});return elements.get(id);}
class FakeWorker{
  constructor(){workers.push(this);this.sent=[];this.terminated=false;}
  postMessage(data){this.sent.push(data);}terminate(){this.terminated=true;}emit(data){this.onmessage({data});}
}
let fetchImpl=async()=>({ok:true,json:async()=>config});
const ctx=vm.createContext({SkeleMotion:{...C,pick:(...args)=>{pickDirection=args[4];return pickedPart;}},document:{getElementById:element},Worker:FakeWorker,fetch:(...args)=>fetchImpl(...args),Float32Array,console});
vm.runInContext(fs.readFileSync(path.join(__dirname,'../motion-ui.js'),'utf8'),ctx);
const parts=['head','torso','arm_left','arm_right','leg_left','leg_right','foot_left','foot_right','tail'].map(name=>({name,label:name}));
const api={canvas:element('canvas'),parts,requestRender(){},mesh:()=>({}),camera:()=>({eye:[0,-10,0],center:[0,0,0],aspect:1,fov:1}),
  normalize:v=>{const l=Math.hypot(...v);return v.map(n=>n/l);},cross:(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]]};
ctx.api=api;const ui=vm.runInContext('createArticulation(api)',ctx),active='job:motion-test';
const items=parts.map(part=>({part,mesh:{positions:new Float32Array(9),low:[-2,-3,-4],high:[4,5,6]}})),e={button:0,clientX:50,clientY:50};
const definitions=[['hip_right','leg_right'],['neck','head'],['shoulder_left','arm_left'],['shoulder_right','arm_right'],['hip_left','leg_left'],['ankle_left','foot_left'],['ankle_right','foot_right'],['tail_root','tail']];
const manifest={schema_version:1,parts,joints:definitions.map(([name,part])=>{const spec=config.hybrid_new.connections.find(s=>s.name===name);return {name,part,center:config.hybrid_new[spec.center_key],direction:spec.mouth_direction,parent:part.startsWith('foot_')?part.replace('foot_','leg_'):'torso'};})};
const pose=()=>JSON.parse(api.canvas.dataset.jointPose),target=()=>JSON.parse(api.canvas.dataset.requestedPose);
const finish=(w,pairs=[])=>w.emit({type:'result',id:w.sent.at(-1).id,pairs,points:new Float32Array(pairs.length?[1,2,3]:[]),computeMs:12});
const key=(key,shiftKey=false)=>api.canvas.handlers.keydown({key,shiftKey,preventDefault(){}});
(async()=>{
  await ui.load(active,items,manifest);let w=workers.at(-1);
  assert.equal(api.canvas.dataset.motionEnabled,'true');assert.equal(api.canvas.dataset.collisionState,'preparing');assert.equal(element('collisionResult').hidden,true);
  assert.equal(w.sent.length,1);assert.equal(w.sent[0].type,'init');assert.notEqual(w.sent[0].parts[0].positions,items[0].mesh.positions);
  assert.equal(w.sent[0].ignoredRegions.length,8);assert.ok(w.sent[0].ignoredRegions.every(r=>r.radius===config.joint.ball_diameter_mm/2+config.printing.clearance_linear_deflection_mm));
  assert.ok(w.sent[0].ignoredRegions.some(r=>r.a==='leg_right'&&r.b==='foot_right'&&r.owner==='leg_right'));
  w.emit({type:'ready'});finish(w);assert.equal(api.canvas.dataset.collisionState,'clear');assert.equal(element('collisionResult').hidden,true);
  assert.equal(ui.selectedPart(),'leg_right');assert.match(element('selectionInfo').textContent,/leg_right.*上下 0.0°.*左右 0.0°.*ねじり 0.0°/);
  assert.equal(ui.pointerDown({...e,altKey:true}),false);pickedPart='torso';assert.equal(ui.pointerDown(e),false);ui.pointerEnd();pickedPart='leg_right';
  assert.equal(ui.pointerDown(e),true);ui.pointerMove(10,-10);
  assert.equal(w.sent.length,3,'a check starts immediately, no debounce or pointer-up required');
  assert.deepEqual(pose().hip_right,[0,0,0],'rendered pose waits for its matching collision result');
  assert.match(element('selectionInfo').textContent,/上下 0.0°/,'angle readout must not get ahead of displayed pose');
  const first=w.sent.at(-1).id;ui.pointerMove(10,-10);ui.pointerMove(10,-10);
  assert.equal(w.sent.length,3,'only one check in flight');
  finish(w,[{a:'torso',b:'leg_right'}]);
  assert.deepEqual(pose().hip_right,[4,4,0]);assert.deepEqual(target().hip_right,[12,12,0]);
  assert.match(element('selectionInfo').textContent,/上下 4.0°.*左右 4.0°/);
  assert.equal(api.canvas.dataset.collisionState,'collision');assert.equal(element('collisionResult').hidden,false);
  assert.match(element('collisionResult').textContent,/torso ↔ leg_right/);
  assert.equal(api.canvas.dataset.collisionRevision,api.canvas.dataset.poseRevision);
  assert.equal(w.sent.length,4,'newest queued pose starts as soon as the previous result arrives');
  assert.ok(w.sent.at(-1).id>first+1,'intermediate backlog was coalesced');
  // Continuous input must not starve output. Never call pointerEnd in this loop.
  for(let n=0;n<12;n++){
    ui.pointerMove(1,-1);ui.pointerMove(1,-1);finish(w,n%2?[{a:'torso',b:'leg_right'}]:[]);
    assert.equal(api.canvas.dataset.draggingJoint,'true');
    assert.equal(api.canvas.dataset.poseRevision,api.canvas.dataset.collisionRevision);
    assert.equal(element('collisionResult').hidden,n%2===0);
  }
  assert.equal(Number(api.canvas.dataset.collisionUpdatesDuringDrag),13,'results update repeatedly while the pointer stays held');
  ui.pointerEnd();finish(w);assert.deepEqual(pose(),target());assert.equal(element('collisionResult').hidden,true);assert.equal(ui.overlay().points.length,0);
  const ankle=config.hybrid_new.ankle_center_right_mm;
  assert.deepEqual(C.point(ui.matrix('foot_right'),ankle),C.point(ui.matrix('leg_right'),ankle));
  pickedPart='foot_right';ui.pointerDown({...e,shiftKey:true});ui.pointerMove(10,0);ui.pointerEnd();finish(w);assert.deepEqual(pose().ankle_right,[0,0,4]);
  assert.equal(ui.selectedPart(),'foot_right');assert.match(element('selectionInfo').textContent,/foot_right.*上下 0.0°.*ねじり 4.0°/,'ankle angles stay relative to the leg');
  key('Home');finish(w);assert.deepEqual(pose().ankle_right,[0,0,0]);assert.ok(pose().hip_right[0]>0);
  key('Escape');finish(w);assert.ok(Object.values(pose()).every(v=>v.every(n=>n===0)));
  assert.match(element('selectionInfo').textContent,/上下 0.0°.*ねじり 0.0°/);
  pickedPart='torso';assert.equal(ui.pointerDown(e),false);assert.equal(ui.selectedPart(),'torso');assert.match(element('selectionInfo').textContent,/固定/);
  const beforeTorso=JSON.stringify(pose()),checksBefore=w.sent.length;
  assert.equal(ui.pointerMove(10,-20),false,'torso drag falls through to camera orbit');ui.pointerEnd();
  key('ArrowUp');key('Home');
  assert.equal(w.sent.length,checksBefore,'torso has no articulation checks');
  assert.equal(JSON.stringify(pose()),beforeTorso);
  assert.equal(Object.keys(pose()).length,8);assert.equal(pose().torso_rotation,undefined);
  assert.deepEqual(ui.matrix('torso'),C.identity());
  pickedPart='foot_right';
  const originalMesh=api.mesh,originalCamera=api.camera;
  api.mesh=()=>({groups:[{part:{name:'foot_right'},low:[-1,-1,-1],high:[1,1,1]}]});
  ui.pointerDown({...e,clientX:80});assert.equal(api.canvas.dataset.partGesture,'twist');assert.equal(element('twistGuide').hidden,false);
  ui.pointerMove((Math.cos(Math.PI/6)-1)*30,15);ui.pointerEnd();finish(w);
  assert.deepEqual(pose().ankle_right,[0,0,30]);assert.equal(element('twistGuide').hidden,true);
  key('Home');finish(w);
  ui.pointerDown(e);assert.equal(api.canvas.dataset.partGesture,'bend');ui.pointerMove(10,-10);ui.pointerEnd();finish(w);
  assert.deepEqual(pose().ankle_right,[4,4,0]);key('Home');finish(w);
  ui.pointerDown({...e,clientX:80,shiftKey:true});ui.pointerMove(10,0);ui.pointerEnd();finish(w);
  assert.deepEqual(pose().ankle_right,[0,0,4]);key('Home');finish(w);
  api.camera=()=>({...originalCamera(),up:[1,0,0]});ui.pointerDown({...e,clientX:75});ui.pointerEnd();
  assert.ok(Math.abs(pickDirection[0])<1e-10&&pickDirection[2]<0,'ray picking uses the rolled camera basis');
  api.camera=originalCamera;pickedPart='leg_right';
  api.mesh=()=>({groups:[{part:{name:'leg_right'},low:[-1,-1,-1],high:[1,1,1]}]});
  ui.pointerDown({...e,clientX:80});ui.pointerMove((Math.cos(Math.PI/6)-1)*30,15);ui.pointerEnd();finish(w);
  assert.deepEqual(pose().hip_right,[0,0,-30],'toward-viewer joint reverses angular sign to follow the visible gesture');
  key('Home');finish(w);
  api.mesh=originalMesh;api.camera=originalCamera;
  console.log('PASS: circular outer-part twist, central bend, Shift override, guide lifecycle and rolled-camera picking');
  pickedPart='foot_right';ui.pointerDown(e);ui.pointerEnd();
  key('ArrowRight',true);finish(w);assert.deepEqual(pose().ankle_right,[0,0,1]);
  const saved=ui.joints().map(j=>({...j,angles:j.name==='hip_right'?[11,12,13]:[0,0,0]}));
  assert.deepEqual(JSON.parse(JSON.stringify(ui.restore({joints:saved}))),{restored:8,total:8});finish(w);assert.deepEqual(pose().hip_right,[11,12,13]);
  const renamed=saved.map(j=>j.name==='hip_right'?{...j,name:'changed_joint',angles:[21,22,23]}:j);
  assert.deepEqual(JSON.parse(JSON.stringify(ui.restore({joints:renamed}))),{restored:8,total:8});finish(w);assert.deepEqual(pose().hip_right,[21,22,23],'renamed joint restores by stable moving part');
  const savedError=w.onerror;w.onerror();assert.equal(api.canvas.dataset.collisionState,'unavailable');assert.equal(w.terminated,true);assert.equal(element('collisionResult').hidden,true);
  key('ArrowUp');assert.equal(api.canvas.dataset.collisionState,'unavailable');assert.equal(element('status').hidden,false);
  w.emit({type:'ready'});finish(w);assert.equal(api.canvas.dataset.collisionState,'unavailable');
  await ui.load(active,items,manifest);const newer=workers.at(-1);savedError();assert.equal(newer.terminated,false);
  newer.emit({type:'ready'});finish(newer);assert.equal(api.canvas.dataset.collisionState,'clear');
  await ui.load('job:no-joints',items);assert.equal(newer.terminated,true);assert.equal(api.canvas.dataset.motionEnabled,'false');assert.equal(api.canvas.dataset.collisionState,'inactive');
  assert.equal(element('collisionResult').hidden,true);assert.deepEqual(ui.matrix('head'),C.identity());
  assert.equal(element('selectionInfo').hidden,true);assert.equal(ui.selectedPart(),null);
  let resolveConfig;fetchImpl=()=>new Promise(resolve=>resolveConfig=resolve);const loading=ui.load(active,items,manifest);ui.clear();resolveConfig({ok:true,json:async()=>config});await loading;assert.equal(api.canvas.dataset.motionEnabled,'false');
  fetchImpl=async()=>({ok:false});await ui.load(active,items,manifest);assert.equal(api.canvas.dataset.collisionState,'unavailable');assert.equal(api.canvas.dataset.motionEnabled,'false');
  fetchImpl=async()=>({ok:true,json:async()=>config});
  const hashed=items.map((item,i)=>({...item,sha256:i.toString(16).padStart(64,'0')}));
  await ui.load(active,hashed,manifest);const resident=workers.at(-1);resident.emit({type:'ready'});finish(resident);
  key('ArrowUp');const staleCheck=resident.sent.at(-1).id;
  ui.clear();assert.equal(resident.terminated,false,'leaving the stage retains one verified collision worker');
  const count=workers.length;await ui.load(active,hashed,manifest);
  assert.equal(workers.length,count);assert.equal(api.canvas.dataset.collisionWorkerReused,'true');
  assert.equal(resident.sent.filter(message=>message.type==='init').length,1,'return does not rebuild BVHs or copy meshes');
  resident.emit({type:'result',id:staleCheck,pairs:[{a:'head',b:'tail'}],points:new Float32Array([1,2,3])});
  assert.equal(api.canvas.dataset.collisionState,'preparing','stale parked checks never certify a new pose');
  finish(resident);assert.equal(ui.reviewState().collision,'clear');assert.equal(ui.reviewState().ready,true);
  ui.clear();resident.onerror();assert.equal(resident.terminated,true);
  await ui.load(active,hashed,manifest);assert.equal(workers.length,count+1,'an errored parked worker is not reused');
  const replacement=workers.at(-1);replacement.emit({type:'ready'});finish(replacement);
  const changed=hashed.map((item,i)=>i?item:{...item,sha256:'f'.repeat(64)});
  await ui.load(active,changed,manifest);assert.equal(replacement.terminated,true,'changed geometry discards the previous BVH');
  assert.equal(api.canvas.dataset.collisionWorkerReused,'false');
  const currentWorker=workers.at(-1);currentWorker.emit({type:'ready'});finish(currentWorker);
  ui.restore({joints:ui.joints().map(j=>({...j,angles:[5,6,7]}))});finish(currentWorker);
  const handoff=ui.continuity(),stableManifest={schema_version:1,parts,joints:ui.joints()};
  await ui.load('job:stable',changed,stableManifest,{parameters:config,continuity:handoff});
  assert.deepEqual(pose().hip_right,[5,6,7],'new geometry is initially shown in the retained pose, not zero pose');
  assert.equal(ui.reviewState().ready,false,'new mesh still requires fresh collision verification');
  const updated=JSON.parse(JSON.stringify(stableManifest));updated.joints.find(j=>j.name==='hip_right').center[0]+=1;
  await ui.load('job:stable',changed,updated,{parameters:config,continuity:handoff});
  assert.deepEqual(pose().hip_right,[0,0,0],'changed axes do not inherit stale pose');
  assert.deepEqual(pose().ankle_right,[0,0,0],'changed ancestor invalidates descendant pose');
  assert.deepEqual(pose().neck,[5,6,7],'unaffected branch retains pose');
  updated.preview_only=true;updated.joints.find(j=>j.name==='hip_right').motion_ready=false;
  await ui.load('job:stable',changed,updated,{parameters:config,continuity:handoff});
  const partialWorker=workers.at(-1);partialWorker.emit({type:'ready'});finish(partialWorker);
  pickedPart='leg_right';assert.equal(ui.pointerDown(e),false,'pending joint cannot be dragged');
  key('ArrowUp');assert.deepEqual(target().hip_right,[0,0,0],'pending joint cannot be changed by keyboard');
  assert.equal(ui.reviewState().ready,false,'partial motion previews cannot certify a print');
  console.log('PASS: immediate continuous collision checks, no pointer-up starvation, tested-pose/overlay atomicity, latest-only queue, collision-only banner, inherited feet, twist/keyboard resets, errors and stale model/configuration races');
})().catch(error=>{console.error(error);process.exitCode=1;});
