const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const elements=new Map();
const timers=new Map();let nextTimer=0;
const glCalls=[];
const SkeleMotion=require('../motion-core.js');
const gl=new Proxy({}, {get:(_,key)=>/^[A-Z_]+$/.test(key)?key:(...args)=>{if(['uniform3fv','uniform1f','drawArrays','deleteBuffer','depthMask','blendFuncSeparate'].includes(key))glCalls.push({key,args});return key==='getUniformLocation'?args[1]:true;}});
function element(id){if(!elements.has(id))elements.set(id,{handlers:{},dataset:{},clientWidth:1000,clientHeight:1000,getBoundingClientRect(){return {left:0,top:0,width:this.clientWidth,height:this.clientHeight};},getContext:()=>gl,addEventListener(name,fn){this.handlers[name]=fn;},setPointerCapture(){},focus(){}});return elements.get(id);}
const source=fs.readFileSync(path.join(__dirname,'../app.js'),'utf8');
const context=vm.createContext({console,performance,Float32Array,ArrayBuffer,DataView,Math,Map,URLSearchParams,SkeleMotion,crypto:require('node:crypto').webcrypto,document:{getElementById:element},window:{addEventListener(){}},requestAnimationFrame(){},setTimeout(fn){timers.set(++nextTimer,fn);return nextTimer;},clearTimeout(id){timers.delete(id);}});
vm.runInContext(source.replace(/start\(\);\s*$/,''),context);
const run=code=>JSON.parse(vm.runInContext('JSON.stringify('+code+')',context));
const b=fs.readFileSync(path.join(__dirname,'../../build/generated_appearance/trex_appearance_200mm_outward.stl'));
context.input=b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength);
const result=run(`(()=>{mesh=parseSTL(input);resetView();return {count:mesh.positions.length/9,finite:mesh.normals.every(Number.isFinite),extent,distance};})()`);
assert.equal(result.count,b.readUInt32LE(80));assert.equal(result.finite,true);assert.ok(result.extent>190&&result.extent<210);
const rayPlacement=run(`(()=>{
  const ray=cameraRay(500,500),surface=ray.origin.map((v,k)=>v+ray.direction[k]*distance),candidate=surface.map((v,k)=>v+ray.direction[k]*6),projected=projectWorld(candidate);
  return {directionLength:Math.hypot(...ray.direction),x:projected.x,y:projected.y};
})()`);
assert.ok(Math.abs(rayPlacement.directionLength-1)<1e-12);
assert.ok(Math.abs(rayPlacement.x-500)<1e-8&&Math.abs(rayPlacement.y-500)<1e-8,'depth placement must stay under the clicked pixel');
const solidHit=run(`(()=>{const hit=raycastSurface(500,500),p=hit&&projectWorld(hit.solidMidpoint);return hit&&{midpoint:hit.solidMidpoint,thickness:hit.thickness_mm,x:p.x,y:p.y};})()`);
assert.ok(solidHit&&solidHit.midpoint.every(Number.isFinite)&&solidHit.thickness>0,'a closed model ray has a solid midpoint');
assert.ok(Math.abs(solidHit.x-500)<1e-8&&Math.abs(solidHit.y-500)<1e-8,'solid midpoint remains under the clicked pixel');
const symmetry=run(`(()=>{
  const original=mesh,faces=[[0,2,1],[0,3,2],[4,5,6],[4,6,7],[0,1,5],[0,5,4],[1,2,6],[1,6,5],[2,3,7],[2,7,6],[3,0,4],[3,4,7]];
  const cube=c=>{const v=[[-1,-1,-1],[1,-1,-1],[1,1,-1],[-1,1,-1],[-1,-1,1],[1,-1,1],[1,1,1],[-1,1,1]].map(p=>[p[0]+c,p[1],p[2]]);return faces.flatMap(f=>f.flatMap(i=>v[i]));};
  mesh={positions:new Float32Array([...cube(-5),...cube(5)]),low:[-6,-1,-1],high:[6,1,1]};
  const pair=mirrorCandidate([-5,0,0],1,{symmetry_mirroring:{axis:'x'}}),middle=mirrorCandidate([0,0,0],1,{symmetry_mirroring:{axis:'x'}}),manual=reflectPoint([-5,0,0],1,{symmetry_mirroring:{axis:'x'}});mesh=original;
  return {center:pair?.center,axis:pair?.axis,middle,manual:manual?.center};
})()`);
assert.deepEqual(symmetry.center,[5,0,0]);assert.equal(symmetry.axis,'x');assert.equal(symmetry.middle,null);
assert.deepEqual(symmetry.manual,[5,0,0]);
const midline=run(`(()=>{const original=mesh;mesh={positions:new Float32Array(9),low:[-10,-5,-5],high:[10,5,5]};const near=snapCandidateToMidline([.8,4,3],2,{midline_snapping:{axis:'x',maximum_offset_radius_ratio:.5}}),side=snapCandidateToMidline([5,4,3],2,{midline_snapping:{axis:'x',maximum_offset_radius_ratio:.5}});mesh=original;return {near,side};})()`);
assert.deepEqual(midline.near.center,[0,4,3]);assert.equal(midline.near.snapped,true);assert.deepEqual(midline.side.center,[5,4,3]);assert.equal(midline.side.snapped,false);
assert.throws(()=>vm.runInContext('parseSTL(new ArrayBuffer(20))',context));
const interaction=run(`(()=>{
  const start=yaw,bytes=mesh.positions[0];
  const e=(id,x,y)=>({pointerId:id,clientX:x,clientY:y,button:0,pointerType:'touch',preventDefault(){}});
  canvas.handlers.pointerdown(e(1,400,400));canvas.handlers.pointermove(e(1,450,425));
  const rotated=yaw!==start;canvas.handlers.pointerdown(e(2,650,425));
  const before=distance;canvas.handlers.pointermove(e(2,750,425));const pinched=distance<before;
  canvas.handlers.pointercancel(e(2,750,425));canvas.handlers.pointerup(e(1,450,425));
  zoom(1e10);const max=distance;zoom(1e-10);const min=distance;resetView();
  return {rotated,pinched,released:pointers.size===0,max,min,extent,yaw,pitch,distance,unchanged:mesh.positions[0]===bytes};
})()`);
assert.equal(interaction.rotated,true);assert.equal(interaction.pinched,true);assert.equal(interaction.released,true);
assert.equal(interaction.max,interaction.extent*8);assert.equal(interaction.min,interaction.extent*.3);
assert.equal(interaction.yaw,-Math.PI/2);assert.equal(interaction.pitch,.1);assert.equal(interaction.distance,interaction.extent*1.55);assert.equal(interaction.unchanged,true);
const rollResult=run(`(()=>{
  const e=(id,x,y)=>({pointerId:id,clientX:x,clientY:y,button:0,pointerType:'touch',preventDefault(){}});
  const oldYaw=yaw,oldPitch=pitch;
  canvas.handlers.pointerdown(e(1,950,500));canvas.handlers.pointermove(e(1,500,950));canvas.handlers.pointerup(e(1,500,950));
  const ringRoll=roll,onlyRoll=yaw===oldYaw&&pitch===oldPitch;
  const camera=cameraParameters(),forward=normalize(camera.center.map((v,k)=>v-camera.eye[k]));
  const orthogonal=Math.abs(dot(forward,camera.up))<1e-10;
  resetView();canvas.handlers.pointerdown(e(1,400,500));canvas.handlers.pointerdown(e(2,600,500));canvas.handlers.pointermove(e(2,400,700));
  const fingerRoll=roll;canvas.handlers.pointercancel(e(2,400,700));canvas.handlers.pointerup(e(1,400,500));resetView();
  return {ringRoll,onlyRoll,orthogonal,fingerRoll,reset:roll,wrap:wrapAngle(-Math.PI*2+.1)};
})()`);
assert.ok(Math.abs(rollResult.ringRoll+Math.PI/2)<1e-10);assert.equal(rollResult.onlyRoll,true);assert.equal(rollResult.orthogonal,true);
assert.ok(Math.abs(rollResult.fingerRoll+Math.PI/2)<1e-10);assert.equal(rollResult.reset,0);assert.ok(Math.abs(rollResult.wrap-.1)<1e-10);
console.log('PASS: outside-ring camera roll, two-finger twist, orthogonal rolled camera, wrap and reset');
const panResult=run(`(()=>{
  const e=(id,x,y,button=1,timeStamp=0)=>({pointerId:id,clientX:x,clientY:y,button,pointerType:'mouse',timeStamp,preventDefault(){}});
  resetView();const initial=center.slice(),initialYaw=yaw,initialPitch=pitch;
  canvas.handlers.pointerdown(e(1,400,400));canvas.handlers.pointermove(e(1,460,430));canvas.handlers.pointerup(e(1,460,430,1,100));
  const panned=center.some((v,k)=>Math.abs(v-initial[k])>1e-8),orientationHeld=yaw===initialYaw&&pitch===initialPitch;
  canvas.handlers.pointerdown(e(2,500,500,1,200));canvas.handlers.pointerup(e(2,500,500,1,210));
  canvas.handlers.pointerdown(e(3,501,501,1,300));canvas.handlers.pointerup(e(3,501,501,1,310));
  return {panned,orientationHeld,reset:center.every((v,k)=>Math.abs(v-initial[k])<1e-8),yaw,pitch};
})()`);
assert.equal(panResult.panned,true);assert.equal(panResult.orientationHeld,true);assert.equal(panResult.reset,true);
assert.equal(panResult.yaw,-Math.PI/2);assert.equal(panResult.pitch,.1);
console.log('PASS: middle drag pans without rotating and middle double-click restores the original view');
const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');
assert.equal((html.match(/<canvas /g)||[]).length,1);
assert.equal((html.split('</header>')[0].match(/<button\b[^>]*>/g)||[]).filter(tag=>!tag.includes(' hidden')).length,2,'only model picker and camera reset are always visible');
assert.ok(/id="modelSelect" hidden/.test(html)&&html.includes('id="modelGallery"')&&html.includes('model-gallery.js'),'the native model select is replaced by an image gallery dialog');
assert.ok(html.includes('id="modelTrashOpen"')&&html.includes('id="modelTrashBack"')&&html.includes('id="modelTrashEmpty"'),'the model gallery exposes trash, restore navigation and permanent bulk deletion');
assert.ok(!/id="machineImage"/.test(html),'machining runs in the background without a header action');
assert.ok(/id="imageUpload"[^>]*type="file"/.test(html));
assert.ok(!/id="uploadImage"/.test(html),'drag and drop is the only image import entry point');
assert.ok(html.includes('workflow-ui.js'));
assert.ok(html.includes('partition-ui.js'));
assert.ok(source.includes('preserveView=')&&source.includes('if(preserveView)requestRender()'),'automatic colour reload preserves the current camera');
assert.ok(source.includes('preserveMesh=preserveView&&Boolean(previousMesh)')&&source.includes('if(!preserveMesh){canvas.dataset.loaded='),'same-job colour reload keeps the old mesh visible until the replacement is ready');
assert.ok(/id="partitionAdjust"[^>]*hidden/.test(html),'partition marking is contextual');
assert.ok(!html.includes('partitionApply'),'partition colours update without a manual preview button');
assert.ok(!/id="returnToPartition"/.test(html),'workflow navigation enters partition editing directly');
assert.ok(!html.includes('machiningConfirm'),'joint machining starts without a confirmation dialog');
assert.ok(!/colorPanel|partLegend|partColors|motionPanel|jointSelect|type="range"|type="checkbox"/.test(html),'no legend, toggles or joint cards');
assert.ok(/id="collisionResult"[^>]*hidden/.test(html),'collision banner hidden by default');
const css=fs.readFileSync(path.join(__dirname,'../style.css'),'utf8');
assert.ok(/\.modelGalleryList[^}]*minmax\(240px,1fr\)[^}]*grid-auto-rows:226px/.test(css)&&/\.modelCard[^}]*height:226px/.test(css)&&/\.modelCardSelect[^}]*grid-template-rows:180px 44px/.test(css),'model gallery uses large fixed-height image cards with a single title row');
assert.ok(!/\.modelCardDescription/.test(css)&&!fs.readFileSync(path.join(__dirname,'../model-gallery.js'),'utf8').includes('modelCardDescription'),'model and trash galleries omit workflow descriptions');
assert.ok(/\.modelGallery \.iconButton,\.modelCardTrash[^}]*place-items:center[^}]*padding:0/.test(css)&&/\.modelCardRestore[^}]*flex:0 0 auto/.test(css),'gallery icons are centered and restore shares the title row without overlap');
const partitionSource=fs.readFileSync(path.join(__dirname,'../partition-ui.js'),'utf8');
assert.ok(partitionSource.includes('joint_ball_diameter_mm')&&css.includes('--range-size'),'joint ball size and partition envelope are rendered separately');
assert.ok(partitionSource.includes('solidMidpoint')&&partitionSource.includes('needsDepthSnap'),'new and legacy user markers use solid depth centering');
assert.ok(partitionSource.includes('symmetry_mirror_x_v1')&&partitionSource.includes('toggle.hidden=true'),'similar opposite geometry is paired and the edit-mode toggle stays hidden');
assert.ok(partitionSource.includes('symmetry_pair_id')&&!partitionSource.includes('dataset.enabled'),'symmetric pairs persist and marker enable toggles are absent');
assert.ok(css.includes('data-symmetry="true"'),'symmetric marker pairs have a distinct colour');
assert.ok(css.includes('data-midline="true"'),'original midline markers have a distinct colour');
assert.ok(!/canvas\.articulated/.test(css),'canvas must remain full viewport');
assert.ok(/#collisionResult[^}]*top:65px/.test(css),'collision banner belongs at the top');
assert.ok(!/cutTopology|sculpt|connector|jointMarker|cutLine/.test(source));
assert.ok(html.includes('poseSnapshots')&&html.includes('snapshotList')&&html.includes('pose-snapshots.js'),'articulated models expose the image snapshot rail');
assert.ok(!html.includes('addSnapshot')&&!html.includes('snapshotNotice'),'snapshot addition lives in the card list without a status line');
assert.ok(!html.includes('snapshotHeader')&&html.includes('snapshotFlash'),'snapshot rail omits its heading and includes camera flash feedback');
const snapshotSource=fs.readFileSync(path.join(__dirname,'../pose-snapshots.js'),'utf8');
assert.ok(snapshotSource.includes('localStorage'),'pose snapshots persist locally');
assert.ok(snapshotSource.includes("filter(item=>item.model===defaultModel)")&&snapshotSource.includes("item.model!==defaultModel"),'pose snapshots are stored and displayed per model');
assert.ok(/\.snapshotRestore img[^}]*aspect-ratio:4\/3[^}]*object-fit:contain/.test(css),'snapshot thumbnails preserve their aspect ratio');
assert.ok(snapshotSource.includes('snapshotCameraIcon')&&!snapshotSource.includes('新規追加'),'snapshot creation is an icon-only camera card');
assert.ok(snapshotSource.includes('items.unshift')&&snapshotSource.indexOf('card(front,true)+addCard()')>=0,'camera card stays below front and saved cards are newest-first');
assert.ok(snapshotSource.includes('draggable="true"')&&snapshotSource.includes("application/x-skelecad-snapshot")&&snapshotSource.includes("addEventListener('drop'"),'saved cards use isolated drag-and-drop reordering');
assert.ok(snapshotSource.includes('resetButton.hidden=active'),'articulated views hide the redundant reset button');
assert.ok(/#poseSnapshots[^}]*scrollbar-gutter:stable/.test(css),'snapshot rail reserves scrollbar space so card size stays fixed');
assert.ok(!/cut_topology|boundary_fill|penPanel|jointControls|cutControls/.test(html));
for(const asset of html.matchAll(/value="\.\.\/(.*?)"/g))assert.ok(fs.existsSync(path.join(__dirname,'../../',asset[1])),asset[1]);
const select=element('modelSelect');
const modelSelectHtml=html.match(/<select id="modelSelect"[^>]*>([\s\S]*?)<\/select>/)[1];
select.options=Array.from(modelSelectHtml.matchAll(/<option value="([^"]+)"/g),match=>({value:match[1]}));
select.value=select.options[0].value;
vm.runInContext("selectInitialModel('?model=../build/hybrid/trex_hybrid_assembly.stl')",context);
assert.equal(select.value,'../build/hybrid/trex_hybrid_assembly.stl');
for(const query of ['?model=https://example.com/evil.stl','?model=../config/toolchain.json','']){
  select.value=select.options[0].value;context.query=query;
  vm.runInContext('selectInitialModel(query)',context);
  assert.equal(select.value,select.options[0].value);
}
console.log('PASS: real STL, malformed input, orbit, pinch, zoom limits, reset, unchanged geometry and no geometry editing code');
console.log('PASS: approved model deep link, unsafe/unknown URL rejection and original default retained');
const config=JSON.parse(fs.readFileSync(path.join(__dirname,'../../config/parameters.json'),'utf8'));
if(config.appearance_candidate){
  const candidate=config.appearance_candidate;
  const activeRoot=config.hybrid_new?.palm_size?.enabled?config.hybrid_new.palm_size.output_directory:config.hybrid_new?.output_directory;
  const activeModel=activeRoot ? '../'+activeRoot+'/trex_hybrid_assembly.stl' : '../'+candidate.mesh;
  assert.equal(select.options[0].value,activeModel);
  if(config.hybrid_new){
    assert.ok(html.includes('新規モデル：1.2.7 ジョイント加工済み'));
    const packaged=JSON.parse(fs.readFileSync(path.join(__dirname,'../../build/reports/hybrid_package.json'),'utf8'));
    if(config.hybrid_new.palm_size?.enabled){
      assert.equal(packaged.appearance_mesh,activeRoot+'/source_scaled.stl');
      const sizing=JSON.parse(fs.readFileSync(path.join(__dirname,'../../',activeRoot,'sizing.json'),'utf8'));
      assert.equal(sizing.original_source.replaceAll('\\','/'),candidate.mesh);
      assert.equal(sizing.source_sha256,require('node:crypto').createHash('sha256').update(fs.readFileSync(path.join(__dirname,'../../',candidate.mesh))).digest('hex'));
    }else assert.equal(packaged.appearance_mesh,candidate.mesh);
    assert.equal('../'+packaged.assembly_review_stl.replaceAll('\\','/'),activeModel);
  }
  assert.ok(html.includes('新規生成：今回の画像（8/30）'));
  assert.ok(html.includes('旧モデル：外観（8/21）'));
  assert.ok(html.includes('精密ジョイント未加工'));
  const current=fs.readFileSync(path.join(__dirname,'../../',candidate.mesh));
  context.input=current.buffer.slice(current.byteOffset,current.byteOffset+current.byteLength);
  const parsed=run('(()=>{const m=parseSTL(input);return {faces:m.positions.length/9,width:m.high[0]-m.low[0]};})()');
  assert.equal(parsed.faces,current.readUInt32LE(80));
  assert.ok(Math.abs(parsed.width-config.hybrid.target_length_mm)<.001);
  const crypto=require('node:crypto');
  const original=fs.readFileSync(path.join(__dirname,'../../',candidate.source_image));
  assert.equal(crypto.createHash('sha256').update(original).digest('hex'),candidate.source_sha256);
  console.log('PASS: current assembly provenance/default, old model labels, unprocessed reference notice, size and source hash');
}

const assemblyPath='../'+config.hybrid_new.output_directory+'/trex_hybrid_assembly.stl';
context.assemblyPath=assemblyPath;
const sources=run('modelSources(assemblyPath)');
assert.equal(sources.length,9);
assert.equal(new Set(sources.map(s=>s.part.color)).size,9);
assert.equal(new Set(sources.map(s=>s.part.name)).size,9);
context.coloredItems=sources.map(s=>{
  const data=fs.readFileSync(path.join(__dirname,'../../',s.path.slice(3)));
  context.input=data.buffer.slice(data.byteOffset,data.byteOffset+data.byteLength);
  return {part:s.part,mesh:vm.runInContext('parseSTL(input)',context)};
});
vm.runInContext('mesh=combineParts(coloredItems)',context);
const coloredMesh=vm.runInContext('mesh',context);
let offset=0;
for(const item of context.coloredItems){
  assert.deepEqual(coloredMesh.positions.slice(offset,offset+item.mesh.positions.length),item.mesh.positions);
  assert.deepEqual(coloredMesh.normals.slice(offset,offset+item.mesh.normals.length),item.mesh.normals);
  offset+=item.mesh.positions.length;
}
const assembly=fs.readFileSync(path.join(__dirname,'../../',assemblyPath.slice(3)));
assert.equal(coloredMesh.positions.length/9,assembly.readUInt32LE(80));
context.input=assembly.buffer.slice(assembly.byteOffset,assembly.byteOffset+assembly.byteLength);
assert.deepEqual(run('parseSTL(input).low'),run('mesh.low'));
assert.deepEqual(run('parseSTL(input).high'),run('mesh.high'));
element('gl').clientWidth=980;element('gl').clientHeight=910;
vm.runInContext('program={};updatePartState();resetView();render()',context);
assert.equal(element('gl').dataset.colorMode,'parts');assert.equal(element('gl').dataset.partCount,'9');
assert.equal(glCalls.filter(c=>c.key==='drawArrays').length,9);
assert.equal(new Set(glCalls.filter(c=>c.key==='uniform3fv').map(c=>JSON.stringify(c.args[1]))).size,9,'part coloring always active');
glCalls.length=0;
vm.runInContext("motion={selectedPart:()=> 'leg_right',matrix:()=>IDENTITY,overlay:()=>({points:new Float32Array(),version:0})};render()",context);
const fades=glCalls.filter(c=>c.key==='uniform1f'&&c.args[0]==='uOpacity').map(c=>c.args[1]);
assert.deepEqual(fades,Array(9).fill(1));
const drawOrder=glCalls.filter(c=>c.key==='drawArrays');
assert.equal(drawOrder.length,9);
assert.deepEqual(glCalls.filter(c=>c.key==='depthMask').map(c=>c.args[0]),[true]);
assert.equal(glCalls.some(c=>c.key==='blendFuncSeparate'),false);
assert.equal(element('gl').dataset.nonSelectedOpacity,'1');
vm.runInContext(`motion.pointerDown=e=>e.clientX===1&&!e.altKey&&e.button===0;
  motion.pointerMove=()=>false;motion.pointerEnd=()=>{};
  function pointer(id,x=100,extra={}){return {pointerId:id,clientX:x,clientY:100,button:0,pointerType:'mouse',preventDefault(){},...extra};}`,context);
function expectOpacity(){
  glCalls.length=0;vm.runInContext('render()',context);
  const actual=glCalls.filter(c=>c.key==='uniform1f'&&c.args[0]==='uOpacity').map(c=>c.args[1]);
  assert.deepEqual(actual,Array(9).fill(1));
  assert.equal(element('gl').dataset.nonSelectedOpacity,'1');
  assert.equal(run('motion.selectedPart()'),'leg_right','camera gesture preserves selection');
}
for(const [x,extra,end] of [[100,{},'pointerup'],[1,{altKey:true},'pointercancel'],[1,{button:1},'lostpointercapture']]){
  context.extra=extra;context.end=end;context.x=x;
  vm.runInContext('canvas.handlers.pointerdown(pointer(1,x,extra))',context);expectOpacity();
  vm.runInContext('canvas.handlers[end](pointer(1,x,extra))',context);expectOpacity();
}
vm.runInContext('canvas.handlers.pointerdown(pointer(1,1))',context);expectOpacity();
vm.runInContext("canvas.handlers.pointerdown(pointer(2,200,{pointerType:'touch'}))",context);expectOpacity();
vm.runInContext('canvas.handlers.pointerup(pointer(2))',context);expectOpacity();
vm.runInContext('canvas.handlers.lostpointercapture(pointer(2))',context);expectOpacity();
vm.runInContext('canvas.handlers.pointercancel(pointer(1))',context);expectOpacity();
vm.runInContext('canvas.handlers.wheel({deltaY:10,preventDefault(){}})',context);expectOpacity();
vm.runInContext('canvas.handlers.wheel({deltaY:10,preventDefault(){}})',context);expectOpacity();
assert.equal(timers.size,0,'no opacity timer is needed');
for(const callback of timers.values())callback();timers.clear();expectOpacity();
vm.runInContext('motion=null',context);
console.log('PASS: all nine parts opaque with a selection and no blending');
console.log('PASS: orbit/Alt/middle/pinch/wheel/part drag and gesture end/cancel/lost capture all stay opaque');
context.singlePath=sources[4].path;
assert.equal(run('modelSources(singlePath)[0].part.name'),'leg_left');
assert.equal(run("modelSources('../build/generated_appearance/20260830_dfba1098/trex_new_200mm.stl')[0].part"),null);
assert.equal(run("modelSources('https://example.com/trex_hybrid_assembly.stl').length"),1);
console.log('PASS: nine permanent part colors, no legend/joint cards, full viewport, hidden top banner, unchanged vertices/normals, exact assembly bounds/facet count, grouped rendering, single-part mapping');

async function testLoading(){
  for(const option of select.options)option.dataset={description:'test model'};
  const requests=[];
  context.fetch=async url=>{requests.push(url);const data=fs.readFileSync(path.join(__dirname,'../../',url.slice(3)));return {ok:true,arrayBuffer:async()=>data.buffer.slice(data.byteOffset,data.byteOffset+data.byteLength)};};
  await vm.runInContext('loadModel(assemblyPath)',context);
  assert.equal(requests.length,9);assert.equal(element('gl').dataset.loaded,'true');
  assert.equal(element('gl').dataset.partCount,'9');assert.equal(element('gl').dataset.colorMode,'parts');
  context.fetch=async()=>({ok:false,status:404});
  await vm.runInContext('loadModel(singlePath)',context);
  assert.equal(vm.runInContext('mesh',context),null);assert.equal(element('gl').dataset.loaded,'false');
  assert.equal(element('gl').dataset.partCount,'0');assert.match(element('status').textContent,/404/);
  const data=fs.readFileSync(path.join(__dirname,'../../',sources[0].path.slice(3)));
  const buffer=data.buffer.slice(data.byteOffset,data.byteOffset+data.byteLength);
  let resolveSlow;
  context.fetch=url=>url===sources[0].path?new Promise(resolve=>{resolveSlow=()=>resolve({ok:true,arrayBuffer:async()=>buffer});}):Promise.resolve({ok:true,arrayBuffer:async()=>buffer});
  context.slowPath=sources[0].path;
  const slow=vm.runInContext('loadModel(slowPath)',context);
  await vm.runInContext('loadModel(singlePath)',context);resolveSlow();await slow;
  assert.equal(element('gl').dataset.model,sources[4].path);
  assert.equal(run('mesh.groups[0].part.name'),'leg_left');
  console.log('PASS: nine-file assembly loading, missing-file failure clears stale model/legend, stale asynchronous load cannot replace current selection');
}
testLoading().catch(error=>{console.error(error);process.exitCode=1;});
