const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const css=fs.readFileSync(path.join(__dirname,'../style.css'),'utf8');
assert.match(css,/#generationPause[^}]*pointer-events:auto/,'pause button remains clickable inside the click-through progress panel');
const nodes=new Map(),events={},timers=[],requests=[],loaded=[];
function node(id){if(!nodes.has(id))nodes.set(id,{hidden:true,dataset:{},handlers:{},value:'',children:[],replaceChildren(){this.children=[];},append(x){this.children.push(x);},showModal(){this.open=true;},close(){this.open=false;},setAttribute(name,value){this[name]=value;},addEventListener(type,fn){this.handlers[type]=fn;},click(){this.clicked=true;}});return nodes.get(id);}
const select=node('modelSelect');select.options=[{value:'legacy'}];select.value='legacy';select.prepend=o=>select.options.unshift(o);
const id='a'.repeat(32),job={id,name:'blue_robot.png',stage:'queued',message:'生成待ち',progress:{value:.25,percent:25,label:'形を組み立て中',remaining_seconds:125,elapsed_seconds:60,estimate_basis:'実測'}};
let catalog=[],cleared=0,partitionBegins=0,partitionLoads=0,deferManifest=false;
const context=vm.createContext({console,Map,Set,Array,URLSearchParams,document:{getElementById:node,createElement:()=>({dataset:{}})},
  window:{addEventListener:(type,fn)=>events[type]=fn,SkelePartition:{load(){partitionLoads++;},begin:()=>partitionBegins++,isActive:()=>false,hasPendingChanges:()=>false,shouldDeferManifest:()=>deferManifest,jobUpdated(){}}},modelSelect:select,canvas:node('gl'),status:node('status'),
  motion:{reviewState:()=>({ready:true,collision:'clear',pose:{j1:[12,0,0]},revision:'2'})},
  releaseMesh(){cleared++;},updatePartState(){},requestRender(){},loadModel:v=>loaded.push(v),
  setTimeout:fn=>timers.push(fn),fetch:async(url,options)=>{
    requests.push({url,...options});
    let body;if(url.endsWith('session'))body={token:'token'};
    else if(url.endsWith('/pause')){job.stage='paused';body=job;}
    else if(url.endsWith('/resume')){job.stage='generating';body=job;}
    else if(url.endsWith('/cancel'))body={id:job.id,stage:'cancelled',deleted:true,message:'生成データを削除しました。'};
    else if(options.method==='POST'){body=job;catalog=[job];}
    else if(/r_[a-f0-9]{32}\.json$/.test(url))body={schema_version:1,parts:[],joints:[{name:'prepared_joint'}]};
    else if(url.endsWith('manifest.json'))body={schema_version:1,parts:[],joints:[]};
    else if(url.endsWith('/'+id))body=job;
    else body={jobs:catalog};
    return {ok:true,json:async()=>body};
  }});
vm.runInContext(fs.readFileSync(path.join(__dirname,'../workflow-ui.js'),'utf8'),context);
const flush=()=>new Promise(resolve=>setImmediate(resolve));
(async()=>{
  await flush();assert.equal(select.value,'legacy');
  node('workflowImage').handlers.click();assert.equal(node('imageUpload').clicked,undefined,'desktop image area retains its original behavior');
  context.window.SkeleMobile={isActive:()=>true};node('workflowImage').handlers.click();
  assert.equal(node('imageUpload').clicked,true,'phone image area opens the existing picker without adding a button');
  delete context.window.SkeleMobile;

  let prevented=0;const file={type:'image/png',size:50,name:'blue_robot.png'};
  events.dragenter({preventDefault(){prevented++;},dataTransfer:{types:['Files']}});
  assert.equal(node('imageDrop').hidden,false);
  events.dragover({preventDefault(){prevented++;},dataTransfer:{types:['Files']}});
  assert.equal(prevented,2);
  events.drop({preventDefault(){},dataTransfer:{files:[file,file]}});await flush();
  assert.match(node('workflowStatus').textContent,/1枚/);assert.equal(cleared,0);
  events.drop({preventDefault(){},dataTransfer:{files:[file]}});await flush();
  assert.equal(cleared,1);assert.equal(select.value,'job:'+id);assert.equal(node('gl').dataset.loaded,'false');
  assert.equal(node('imageDrop').hidden,true);
  assert.equal(node('generationProgress').hidden,false);assert.equal(node('generationProgressBar').value,.25);
  assert.equal(node('generationPause').hidden,false);assert.equal(node('generationStop').hidden,false);
  await node('generationPause').handlers.click();assert.equal(job.stage,'paused');assert.equal(node('generationPause').textContent,'▶');
  await node('generationPause').handlers.click();assert.equal(job.stage,'generating');assert.equal(node('generationPause').textContent,'Ⅱ');
  assert.match(node('generationProgressText').textContent,/25%/);assert.match(node('generationProgressText').textContent,/残り約2分05秒/);
  const post=requests.find(r=>r.method==='POST');assert.equal(post.headers['X-SkeleCAD-Token'],'token');assert.equal(post.body,file);
  job.stage='appearance_ready';delete job.progress;job.manifest='../api/jobs/'+id+'/files/manifest.json';job.message='外観完了';
  timers.shift()();await flush();assert.deepEqual(loaded,['job:'+id]);
  timers.shift()();await flush();assert.equal(loaded.length,1,'unchanged job does not repeatedly reload the model');
  deferManifest=true;job.manifest_sha256='intermediate';timers.shift()();await flush();
  assert.equal(loaded.length,1,'an intermediate manifest is not loaded over a newer marker operation');
  deferManifest=false;job.manifest_sha256='latest';timers.shift()();await flush();
  assert.equal(loaded.length,2,'the latest completed manifest loads after pending marker operations finish');
  select.value='legacy';select.handlers.change();timers.shift()();await flush();
  assert.equal(loaded.length,2,'background completion never overrides another selected model');
  assert.equal(node('workflowStatus').hidden,true);
  await context.window.SkeleCADWorkflow.manifest(id);assert.equal(loaded.length,2);
  await assert.rejects(context.window.SkeleCADWorkflow.manifest('../private'));
  select.value='job:'+id;job.partition_revision='c'.repeat(32);job.preview_part_count=2;job.manifest_sha256='partition-geometry';
  job.background={stage:'failed',error:'マーカー3番: axis unavailable'};
  context.window.SkeleCADWorkflow.restoreJob(job);
  assert.equal(node('step2').dataset.state,'failed','machining failure points to the partition to edit');
  assert.equal(node('step3').dataset.state,'warning','failed machining warns about partial motion');
  assert.equal(node('step4').disabled,true,'machining errors block print preparation');
  assert.match(node('workflowHint').textContent,/マーカー3番/);
  job.background={stage:'working'};
  context.window.SkeleCADWorkflow.restoreJob(job);
  assert.equal(node('step3').dataset.state,'loading','background machining shows a spinner');
  assert.equal(node('step3').disabled,false,'processing allows entering the motion view');
  assert.equal(node('step1').dataset.state,'ready','earlier stages remain navigable');
  assert.equal(node('step4').disabled,true,'print preparation waits for background machining');
  const waitingLoads=loaded.length;
  await node('step4').handlers.click();
  assert.equal(loaded.length,waitingLoads,'disabled print action cannot navigate');
  const waitingMutations=requests.filter(r=>r.method==='POST').length;
  context.window.SkelePartition.hasPendingChanges=()=>true;
  await node('step3').handlers.click();
  assert.equal(node('step3').dataset.current,'true');
  assert.equal(requests.filter(r=>r.method==='POST').length,waitingMutations,'entering during partition neither cancels nor queues duplicate work');
  assert.match(node('workflowHint').textContent,/準備中/);
  context.window.SkelePartition.hasPendingChanges=()=>false;
  const beforeReady=loaded.length;
  job.background={stage:'mechanical_ready',revision:'d'.repeat(32)};
  job.background.manifest_sha256='prepared-background';
  catalog=[job];timers.shift()();await flush();
  assert.ok(loaded.length>beforeReady,'background completion reloads the viewed motion stage automatically');
  const preparedMotion=await context.window.SkeleCADWorkflow.manifest(id);
  assert.equal(preparedMotion.joints[0].name,'prepared_joint','the reload uses the prepared revision, not the partition preview');
  context.window.SkeleCADWorkflow.restoreJob(job);
  assert.equal(node('step3').dataset.state,'ready','finished machining stops the spinner');
  assert.equal(node('step4').dataset.state,'loading','background slicing has its own spinner');
  assert.equal(node('step4').disabled,true,'background slicing blocks print preparation');
  job.background={stage:'ready',revision:'d'.repeat(32)};
  context.window.SkeleCADWorkflow.restoreJob(job);
  assert.equal(node('step4').dataset.state,'ready');
  assert.equal(node('step4').disabled,false);
  for(const stage of ['partitioning','machining','paused','partition_failed','machining_failed','print_failed']){
    job.stage=stage;context.window.SkeleCADWorkflow.restoreJob(job);
    assert.equal(node('step4').disabled,true,stage+' blocks even a previous ready result');
  }
  job.stage='appearance_ready';
  context.window.SkelePartition.hasPendingChanges=()=>true;
  context.window.SkeleCADWorkflow.restoreJob(job);
  assert.equal(node('step4').disabled,true,'unsaved marker changes block old print preparation');
  context.window.SkelePartition.hasPendingChanges=()=>false;
  context.window.SkeleCADWorkflow.restoreJob(job);
  await context.window.SkeleCADWorkflow.manifest(id);assert.equal(nodes.has('machineImage'),false);
  assert.equal(node('step3').disabled,false,'background result enables joint navigation');
  await node('step3').handlers.click();
  const machine=requests.find(r=>r.url.endsWith('/machine'));assert.equal(JSON.parse(machine.body).manifest_sha256,'partition-geometry');
  assert.equal(node('machiningConfirm').open,undefined,'machining has no confirmation dialog');
  select.value='job:'+id;job.stage='mechanical_review';job.manifest_sha256='current-geometry';job.mechanical_revision='b'.repeat(32);
  await context.window.SkeleCADWorkflow.manifest(id);
  assert.equal(nodes.has('machineImage'),false);assert.equal(node('returnToPartition').hidden,true);
  const mutations=requests.filter(r=>r.method==='POST').length;
  context.window.SkelePartition.hasPendingChanges=()=>true;
  await node('step1').handlers.click();
  assert.equal(node('step1').dataset.current,'true','pending partition saves allow navigating back');
  const partitionLoadsBefore=partitionLoads;
  await context.window.SkeleCADWorkflow.manifest(id);
  assert.equal(partitionLoads,partitionLoadsBefore,'appearance viewing must not replace pending markers');
  await node('step0').handlers.click();
  assert.equal(node('step0').dataset.current,'true');
  assert.match(node('workflowSource').src,/source\.png\?display=1$/,'image stage requests the lightweight display instead of the source PNG');
  assert.equal(node('workflowSource').fetchPriority,'high');
  assert.equal(requests.filter(r=>r.method==='POST').length,mutations,'viewing earlier stages neither cancels nor rebuilds');
  context.window.SkelePartition.hasPendingChanges=()=>false;

  await node('step2').handlers.click();
  assert.equal(node('returnToPartition').hidden,true);
  assert.ok(partitionBegins>0,'partition navigation immediately enables editing');
  assert.equal(requests.filter(r=>r.method==='POST').length,mutations,'navigation does not invalidate machining');
  await node('step3').handlers.click();
  assert.equal(node('step3').dataset.current,'true');
  await node('step2').handlers.click();
  await context.window.SkeleCADWorkflow.ensureEditable(id);
  const repartition=requests.find(r=>r.url.endsWith('/repartition'));assert.equal(repartition.body,'{}');assert.ok(partitionBegins>0);
  assert.equal(loaded.at(-1),'job:'+id);
  job.stage='mechanical_review';job.mechanical_revision='b'.repeat(32);await context.window.SkeleCADWorkflow.manifest(id);
  const before=requests.filter(r=>r.method==='POST').length;
  await node('step4').handlers.click();
  assert.equal(node('step3').dataset.current,'true','fixed action navigates to joints');
  assert.equal(node('step4').dataset.current,'false','fixed action is not a fifth stage');
  assert.ok(requests.some(r=>r.url.endsWith('/print')),'print action requests reviewed print preparation');
  job.stage='print_ready';
  await context.window.SkeleCADWorkflow.manifest(id);
  await flush();
  await node('step1').handlers.click();
  await node('step4').handlers.click();
  assert.equal(node('step3').dataset.current,'true','prepared jobs also navigate to joints');
  assert.ok(requests.some(r=>r.url.endsWith('/open-print')),'prepared print action opens Bambu Studio');
  const localPosts=requests.filter(r=>r.method==='POST').length;let directCalls=0;
  context.window.location={hostname:'viewer.test-tailnet.ts.net'};
  context.window.SkeleRemotePrint={async open(remoteJob,review,isCurrent){directCalls++;assert.equal(remoteJob.id,id);assert.equal(review.collision,'clear');assert.equal(isCurrent(),true);}};
  context.window.SkeleCADWorkflow.refreshControls();
  assert.equal(node('printStepActionText').textContent,'開始');
  await node('step4').handlers.click();assert.equal(directCalls,1);
  assert.equal(requests.filter(r=>r.method==='POST').length,localPosts,'remote action never uses local prepare/open endpoints');
  context.window.location={hostname:'127.0.0.1'};context.window.SkeleCADWorkflow.refreshControls();
  assert.equal(node('printStepActionText').textContent,'準備');
  const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');
  assert.doesNotMatch(html,/id="(?:openBambu|preparePrint)"/,'no duplicate header actions');
  assert.equal(html.match(/<button id="step4"[^>]*>([\s\S]*?)<\/button>/)[1].replace(/<[^>]*>/g,''),'プリント準備');
  await node('step1').handlers.click();
  job.stage='printing';context.window.SkeleCADWorkflow.restoreJob(job);
  assert.equal(node('step1').dataset.current,'true','a worker stage change does not steal the viewed stage');
  assert.equal(node('step0').disabled,false);assert.equal(node('step1').disabled,false,'completed earlier stages stay available during work');
  job.stage='print_ready';job.manifest_sha256='delayed-manifest';
  let current=true,finishRead;const fetchBefore=context.fetch;
  context.fetch=()=>new Promise(resolve=>{finishRead=()=>resolve({ok:true,json:async()=>({parts:[],geometry:{sha256:'shape'}})});});
  const loadsBefore=partitionLoads,stale=context.window.SkeleCADWorkflow.manifest(id,()=>current);
  await flush();current=false;finishRead();
  assert.equal(await stale,null);assert.equal(partitionLoads,loadsBefore,'a late manifest cannot replace another stage marker state');
  context.fetch=fetchBefore;
  // A partial export that later fails the assembly audit remains view-only.
  delete job.mechanical_revision;job.stage='partitioning';delete job.background;
  job.previous_motion={revision:'f'.repeat(32),manifest_sha256:'previous-nearby',changed_marker_names:['edited'],changed_regions:[{center:[0,0,0],radius_mm:6}]};
  context.window.SkeleCADWorkflow.restoreJob(job);
  await node('step3').handlers.click();
  context.fetch=async()=>({ok:true,json:async()=>({parts:[],joints:[{name:'edited',center:[0,0,0],radius_mm:6},{name:'unchanged',center:[1,0,0],radius_mm:6}]})});
  const retained=await context.window.SkeleCADWorkflow.manifest(id);
  assert.equal(retained.joints[0].motion_ready,false);
  assert.equal(retained.joints[1].motion_ready,true,'nearby unchanged joint remains movable on the previous validated assembly');
  assert.equal(retained.preview_only,true);assert.equal(retained.print_ready,false);
  context.window.SkelePartition.pendingMarkers=()=>[{name:'edited',center:[0,0,0],radius_mm:6},{name:'unchanged',center:[2,0,0],radius_mm:6}];
  const localEdited=await context.window.SkeleCADWorkflow.manifest(id);
  assert.equal(localEdited.joints[1].motion_ready,false,'unsaved edits still lock the edited joint');
  delete context.window.SkelePartition.pendingMarkers;delete job.previous_motion;
  context.fetch=fetchBefore;
  delete job.mechanical_revision;job.stage='appearance_ready';
  job.background={stage:'failed',preview:{revision:'e'.repeat(32),manifest_sha256:'partial-audit-failed',ready_joint_count:1}};
  context.window.SkeleCADWorkflow.restoreJob(job);
  await node('step3').handlers.click();
  context.fetch=async()=>({ok:true,json:async()=>({parts:[],joints:[{name:'partial',motion_ready:true}],preview_only:true,print_ready:false})});
  const failedPreview=await context.window.SkeleCADWorkflow.manifest(id);
  assert.equal(failedPreview.joints[0].motion_ready,false);
  assert.equal(failedPreview.print_ready,false);
  context.fetch=fetchBefore;
  delete job.background;delete job.appearance_symmetry;delete job.mechanical_revision;job.stage='appearance_ready';
  select.value='job:'+id;context.window.SkeleCADWorkflow.restoreJob(job);await node('step1').handlers.click();
  assert.equal(node('workflowTools').hidden,false);assert.equal(node('openSymmetry').hidden,false);
  node('openSymmetry').handlers.click();assert.equal(node('symmetryDialog').open,true);
  assert.equal(node('symmetryOriginal')['aria-pressed'],'true');
  let posts=requests.filter(r=>r.method==='POST').length;
  await node('symmetryApply').handlers.click();assert.equal(requests.filter(r=>r.method==='POST').length,posts,'unchanged original selection never triggers machining');
  node('openSymmetry').handlers.click();node('symmetryLeft').handlers.click();node('symmetryClose').handlers.click();
  assert.equal(requests.filter(r=>r.method==='POST').length,posts,'closing the modal never changes geometry');
  job.mechanical_revision='saved-joints';job.stage='mechanical_review';context.window.SkeleCADWorkflow.restoreJob(job);
  const repartitionsBefore=requests.filter(r=>r.url.endsWith('/repartition')).length;
  node('openSymmetry').handlers.click();node('symmetryRight').handlers.click();await node('symmetryApply').handlers.click();
  assert.equal(requests.filter(r=>r.url.endsWith('/repartition')).length,repartitionsBefore,'symmetry switch must preserve the current completed joint state');
  const submitted=requests.findLast(r=>r.url.endsWith('/symmetry'));assert.equal(JSON.parse(submitted.body).source_side,'positive_x');
  job.appearance_symmetry={active:true,source_side:'positive_x'};context.window.SkeleCADWorkflow.restoreJob(job);
  assert.equal(context.window.SkeleCADWorkflow.stateKey(id),'job:'+id+':positive_x');
  node('openSymmetry').handlers.click();assert.equal(node('symmetryRight')['aria-pressed'],'true','the currently applied choice is shown when reopening');
  node('symmetryOriginal').handlers.click();await node('symmetryApply').handlers.click();assert.ok(requests.findLast(r=>r.url.endsWith('/restore-symmetry')));
  await node('step0').handlers.click();assert.equal(node('workflowTools').hidden,true);assert.equal(node('openSymmetry').hidden,true);
  select.value='legacy';select.handlers.change();
  delete job.mechanical_revision;job.stage='generating';catalog=[job];select.value='job:'+id;timers.shift()();await flush();
  await node('generationStop').handlers.click();assert.ok(requests.some(r=>r.url.endsWith('/cancel')));assert.equal(select.value,'legacy');assert.equal(node('generationProgress').hidden,true);
  console.log('PASS: desktop drag/drop and mobile image-area import, queue feedback, source isolation, hash-manifest load, no refresh loop or background selection hijack');
  console.log('PASS: background machining adoption, reversible partition, fixed print action navigates to joints and model switching');
})().catch(error=>{console.error(error);process.exitCode=1;});
